sudo: required

language: android

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-27
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license.*'

addons:
  apt:
    packages:
      - xvfb

cache:
  directories:
    - node_modules
    - platforms
    - plugins

before_install:
  # Add node.js dependencies.
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install nodejs
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - node -v && npm -v && yarn -v

install:
  - sudo npm install -g cordova
  - yarn

{{#if_or unit e2e}}
before_script:
  - export DISPLAY=':99.0'
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  {{#e2e}}
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation xdg-utils
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  {{/e2e}}
{{/if_or}}

script:
  {{#if_or unit e2e}}
  - yarn test
  {{/if_or}}
  - yarn build
  - yarn build:android
  # - yarn release:android
  # - mv ./platforms/android/app/build/outputs/apk/release/app-release.apk cordova-vue-test2_$TRAVIS_TAG.apk

# deploy:
#   provider: releases
#   skip-cleanup: true
#   overwrite: true
#   api_key: $GH_TOKEN
#   file: 
#     - "cordova-vue-test2_$TRAVIS_TAG.apk"
#   on:
#     tags: true
